/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.DangNhapAdminDAL;
import DAL.DangNhapDAL;
import static DAL.Database.CapNhatTrangThaiMuon;
import DAL.DocGiaDAL;
import DAL.ThuThuDangNhapDAL;
import DTO.DangNhapDTO;
import javax.swing.JOptionPane;
import LuuDN.Luu;
import java.io.File;

/**
 *
 * @author Admin
 */
public class DangNhapUI extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapUI
     */
    private void hienThiLaiThongTinDangNhap() {
        File f = new File("login.data");
        if (f.exists()) {
            Object data = Luu.readData("login.data");
            if (data != null) {
                DangNhapDTO dn = (DangNhapDTO) data;
                txtUserName.setText(dn.getTENDN());
                txtPassword.setText(dn.getMATKHAU());
                DangNhapDTO tt = (DangNhapDTO) data;
                txtUserName.setText(tt.getTENDN());
                txtPassword.setText(tt.getMATKHAU());
                chkSave.setSelected(true);
            }
        }
    }

    protected void xuLyDangNhap() {
        DangNhapDAL dnService = new DangNhapDAL();
        ThuThuDangNhapDAL ttService = new ThuThuDangNhapDAL();
        DangNhapAdminDAL ad = new DangNhapAdminDAL();
        DangNhapDTO dn = dnService.DangNhap(txtUserName.getText(), txtPassword.getText());
        DangNhapDTO tt = ttService.DangNhap(txtUserName.getText(), txtPassword.getText());
        DangNhapDTO admin = ad.DangNhap(txtUserName.getText(), txtPassword.getText());

        if (dn != null) {

            JOptionPane.showMessageDialog(null, "Đăng nhập thành công");
            if (chkSave.isSelected()) {
                Luu.saveData(dn, "login.data");
            } else {
                Luu.saveData(null, "login.data");
            }
//            MenuDocGia dg = new MenuDocGia();
//            dg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//            dg.setLocationRelativeTo(null);
//            dg.setVisible(true);
            new MenuDocGia().setVisible(true);
            this.dispose();

        } else if (tt != null) {
            JOptionPane.showMessageDialog(null, "Đăng nhập thành công");
            if (chkSave.isSelected()) {
                Luu.saveData(tt, "login.data");
            } else {
                Luu.saveData(null, "login.data");
            }
//            MenuThuThu dg = new MenuThuThu();
//            dg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//            dg.setLocationRelativeTo(null);
//            dg.setVisible(true);
            MenuThuThu menu=new MenuThuThu();
            menu.setState(this.txtUserName.getText());
            menu.setVisible(true);
            this.dispose();
//            switch(tt.getLoaiTK()){
//                case "thu thu":{
//                                MenuThuThu dg = new MenuThuThu();
//            dg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//            dg.setLocationRelativeTo(null);
//            dg.setVisible(true);
//                }
//                case "doc gia":{
//                                    MenuDocGia dg = new MenuDocGia();
//            dg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//            dg.setLocationRelativeTo(null);
//            dg.setVisible(true);
//                }
//            }

        } else {
            if (admin != null) {
                {
                    JOptionPane.showMessageDialog(null, "Đăng nhập thành công");
                    if (chkSave.isSelected()) {
                        Luu.saveData(admin, "login.data");
                    } else {
                        Luu.saveData(null, "login.data");
                    }
                    new quanlinhanvien().setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Đăng nhập thất bại");
            }
        }

    }

    public DangNhapUI() {
        initComponents();
        CapNhatTrangThaiMuon();
        hienThiLaiThongTinDangNhap();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        chkSave = new javax.swing.JCheckBox();
        btnHuy = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DANGNHAP_ = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐĂNG NHẬP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 250));

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        chkSave.setText("Tự động đăng nhập lần sau");
        chkSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSaveActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(204, 0, 0));
        btnHuy.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\shutdown.png")); // NOI18N
        btnHuy.setText("Đăng xuất");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Tên tài khoản");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu");

        DANGNHAP_.setBackground(new java.awt.Color(0, 204, 51));
        DANGNHAP_.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DANGNHAP_.setText("Đăng nhập");
        DANGNHAP_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DANGNHAP_MouseClicked(evt);
            }
        });
        DANGNHAP_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DANGNHAP_ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\library_cms_preview_80_80.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(DANGNHAP_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(btnHuy)
                .addGap(45, 45, 45))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkSave)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DANGNHAP_)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void chkSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSaveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_chkSaveActionPerformed

//    private void hienThiLaiThongTinDangNhap() {
//		File f=new File("login.data");
//		if(f.exists())
//		{
//			Object data=Luu.readData("login.data");
//			if(data!=null)
//			{
//				DangNhapDTO dn=(DangNhapDTO) data;
//				txtUserName.setText(dn.getTENDN());
//				txtPassword.setText(dn.getMATKHAU());
//                                DangNhapDTO tt=(DangNhapDTO) data;
//				txtUserName.setText(tt.getTENDN());
//				txtPassword.setText(tt.getMATKHAU());
//				chkSave.setSelected(true);
//			}
//		}
//	}
//  
//    protected void xuLyDangNhap() {
//		DocGiaDNService dnService=new DocGiaDNService();
//                 ThuThuDNService ttService= new ThuThuDNService();
//		DangNhapDTO dn=dnService.DangNhap(txtUserName.getText(), txtPassword.getText());
//                DangNhapDTO tt=ttService.DangNhap(txtUserName.getText(), txtPassword.getText());
//		if(dn!=null)
//		{
//                    
//			JOptionPane.showMessageDialog(null, "Đăng nhập thành công");
//                        if(chkSave.isSelected())
//			{
//				Luu.saveData(dn, "login.data");
//			}
//			else
//			{
//				Luu.saveData(null, "login.data");
//			}
//                        MenuDocGia dg= new MenuDocGia();
//                        dg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//                        dg.setLocationRelativeTo(null);
//                        dg.setVisible(true);
//
//		}
//                else if(tt!=null)
//		{
//                    JOptionPane.showMessageDialog(null, "Đăng nhập thành công");
//                        if(chkSave.isSelected())
//			{
//				Luu.saveData(tt, "login.data");
//			}
//			else
//			{
//				Luu.saveData(null, "login.data");
//			}
//                        MenuThuThu dg=new MenuThuThu();
//                         dg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//                         dg.setLocationRelativeTo(null);
//                         dg.setVisible(true);
//			
//		}
//                else
//                {
//                    JOptionPane.showMessageDialog(null, "Đăng nhập thất bại");
//                }
//	}
    private void DANGNHAP_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DANGNHAP_MouseClicked
        // TODO add your handling code here:
        xuLyDangNhap();

    }//GEN-LAST:event_DANGNHAP_MouseClicked

    private void DANGNHAP_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DANGNHAP_ActionPerformed
        // TODO add your handling code here:
        xuLyDangNhap();

    }//GEN-LAST:event_DANGNHAP_ActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling c
//        txtPassword.setText("");
//        txtUserName.setText("");
//        txtUserName.requestFocus();
        System.exit(0);
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapUI dn = new DangNhapUI();
                dn.setTitle("THƯ VIỆN TRƯỜNG THPT DƯỠNG ĐIỀM");
                dn.setLocationRelativeTo(null);
                dn.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DANGNHAP_;
    private javax.swing.JButton btnHuy;
    private javax.swing.JCheckBox chkSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
