/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.DoiMatKhauDAL;
import DTO.DoiMatKhauDTO;

/**
 *
 * @author sam
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnDoiTK = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtMatKhauNhapLai = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtMatKhauCu = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đổi mật khẩu");

        jPanel3.setPreferredSize(new java.awt.Dimension(1210, 400));
        jPanel3.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Tên tài khoản");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(330, 150, 76, 31);

        txtTenTK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtTenTK.setPreferredSize(new java.awt.Dimension(5, 20));
        jPanel3.add(txtTenTK);
        txtTenTK.setBounds(450, 150, 184, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Mật khẩu cũ ");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(330, 210, 71, 22);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Mật khẩu mới");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(330, 260, 73, 25);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Nhập lại mật khẩu");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(330, 300, 97, 26);

        btnDoiTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thay đổi.png"))); // NOI18N
        btnDoiTK.setText("Thay đổi");
        btnDoiTK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnDoiTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiTKActionPerformed(evt);
            }
        });
        jPanel3.add(btnDoiTK);
        btnDoiTK.setBounds(409, 360, 100, 30);

        btnHuy.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ICON-20190611T140320Z-001\\ICON\\delete.png")); // NOI18N
        btnHuy.setText("Huỷ");
        btnHuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel3.add(btnHuy);
        btnHuy.setBounds(637, 356, 90, 30);

        txtMatKhauNhapLai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtMatKhauNhapLai.setPreferredSize(new java.awt.Dimension(5, 20));
        jPanel3.add(txtMatKhauNhapLai);
        txtMatKhauNhapLai.setBounds(450, 300, 184, 30);

        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtMatKhauMoi.setPreferredSize(new java.awt.Dimension(5, 20));
        jPanel3.add(txtMatKhauMoi);
        txtMatKhauMoi.setBounds(450, 250, 184, 30);

        txtMatKhauCu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtMatKhauCu.setMinimumSize(new java.awt.Dimension(5, 20));
        txtMatKhauCu.setPreferredSize(new java.awt.Dimension(5, 20));
        jPanel3.add(txtMatKhauCu);
        txtMatKhauCu.setBounds(450, 200, 184, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("ĐỔI MẬT KHẨU TÀI KHOẢN");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(380, 50, 310, 42);

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel3.add(jLabel15);
        jLabel15.setBounds(120, 120, 770, 310);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/shutdown.png"))); // NOI18N
        jButton3.setText("Đăng xuất");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuat(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(770, 480, 120, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ICON-20190611T140320Z-001\\ICON\\back.png")); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(120, 480, 110, 34);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\2397.jpg_wh1200.jpg")); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 570);

        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 1000, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoiTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiTKActionPerformed
        // TODO add your handling code here:
        new DoiMatKhauDAL().DoiMatKhau(new DoiMatKhauDTO(txtTenTK.getText(), txtMatKhauCu.getText(), txtMatKhauMoi.getText(), txtMatKhauNhapLai.getText()));
    }//GEN-LAST:event_btnDoiTKActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        // System.exit(0);
        txtTenTK.setText("");
        txtMatKhauCu.setText("");
        txtMatKhauMoi.setText("");
        txtMatKhauNhapLai.setText("");
        txtTenTK.requestFocus();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void DangXuat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuat
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_DangXuat

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuThuThu mn= new MenuThuThu();
        mn.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        mn.setLocationRelativeTo(null);
       this.dispose();
        mn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiTK;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtMatKhauNhapLai;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables
}
