/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class MenuThuThu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ThuThuUI
     */
    public MenuThuThu() {
        initComponents();
        this.BQuanLiDanhMuc.addActionListener(this);
        this.BQuanLiDocGia.addActionListener(this);
        this.BQuanLiMuonTra.addActionListener(this);
      //  this.BQuanLiNhanVien.addActionListener(this);
        this.BThongKe.addActionListener(this);
        this.BTimKiem.addActionListener(this);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BQuanLiDanhMuc = new javax.swing.JButton();
        BQuanLiMuonTra = new javax.swing.JButton();
        BQuanLiDocGia = new javax.swing.JButton();
        BThongKe = new javax.swing.JButton();
        BTimKiem = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THƯ VIỆN TRƯỜNG THPT DƯỠNG ĐIỀM");
        setMinimumSize(new java.awt.Dimension(800, 400));
        setSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(null);

        BQuanLiDanhMuc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BQuanLiDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/quản lý danh mục.png"))); // NOI18N
        BQuanLiDanhMuc.setText("Quản lí  danh mục");
        BQuanLiDanhMuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(BQuanLiDanhMuc);
        BQuanLiDanhMuc.setBounds(30, 10, 150, 72);

        BQuanLiMuonTra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BQuanLiMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cho mượn.png"))); // NOI18N
        BQuanLiMuonTra.setText("Quản lí mượn, trả");
        BQuanLiMuonTra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        BQuanLiMuonTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQuanLiMuonTraActionPerformed(evt);
            }
        });
        jPanel1.add(BQuanLiMuonTra);
        BQuanLiMuonTra.setBounds(200, 10, 150, 74);

        BQuanLiDocGia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BQuanLiDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/quản lý độc giả.png"))); // NOI18N
        BQuanLiDocGia.setText("Quản lý độc giả");
        BQuanLiDocGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(BQuanLiDocGia);
        BQuanLiDocGia.setBounds(30, 100, 150, 74);

        BThongKe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thống kê, báo cáo.png"))); // NOI18N
        BThongKe.setText("Thống kê, báo cáo");
        BThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        BThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThongKeActionPerformed(evt);
            }
        });
        jPanel1.add(BThongKe);
        BThongKe.setBounds(380, 100, 140, 74);

        BTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tìm kiếm.png"))); // NOI18N
        BTimKiem.setText("Tìm kiếm sách");
        BTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(BTimKiem);
        BTimKiem.setBounds(200, 100, 150, 74);

        jButton1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton1.setText("Đổi mật khẩu ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 10, 140, 74);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 115, 550, 190);

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chức năng chính");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 60, 205, 32);

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PHẦN MỀM QUẢN LÝ THƯ VIỆN");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 670, 37);

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/shutdown.png"))); // NOI18N
        jButton7.setText("Đăng xuất");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(640, 320, 113, 30);

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 320, 110, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\thu_vien_5_zing.jpg")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(960, 600));
        jLabel3.setMinimumSize(new java.awt.Dimension(960, 600));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 850, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DoiMatKhau dn= new DoiMatKhau();
        dn.setLocationRelativeTo(null);
        dn.dispose();
        dn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DangNhapUI dn= new DangNhapUI();
        dn.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dn.setLocationRelativeTo(null);
        this.dispose();
        dn.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThongKeActionPerformed
        // TODO add your handling code here:
         thongkebaocao dn= new thongkebaocao();
        dn.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dn.setLocationRelativeTo(null);
        this.dispose();
        dn.setVisible(true);
    }//GEN-LAST:event_BThongKeActionPerformed

    private void BQuanLiMuonTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQuanLiMuonTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BQuanLiMuonTraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuThuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuThuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuThuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuThuThu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuThuThu tt= new MenuThuThu();
                tt.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                tt.setLocationRelativeTo(null);
                tt.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BQuanLiDanhMuc;
    private javax.swing.JButton BQuanLiDocGia;
    private javax.swing.JButton BQuanLiMuonTra;
    private javax.swing.JButton BThongKe;
    private javax.swing.JButton BTimKiem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private String state;

    public void setState(String state) {
        this.state = state;
    }
    @Override
    public String toString(){
        return state;
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource().equals(BTimKiem)){
            try {
                new Timkiem().setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(MenuThuThu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(ae.getSource().equals(BQuanLiDocGia)){
            new quanlidocgia().setVisible(true);
            this.dispose();
        }
//        if(ae.getSource().equals(BQuanLiNhanVien)){
//            new quanlinhanvien().setVisible(true);
//            this.dispose();
//        }
        if(ae.getSource().equals(BQuanLiMuonTra)){
           quanlimuontra ql= new quanlimuontra();
           ql.setState(state);
           ql.setVisible(true);
            this.dispose();
        }
        if(ae.getSource().equals(BQuanLiDanhMuc)){
            new quanlydanhmuc().setVisible(true);
            this.dispose();
        }
    }
}
