/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.PhieuNhapSachBLL;
import DAL.PhieuNhapSachDAL;
import DAL.QuanLyDanhMucServices;

import DTO.NXBDTO;
import DTO.PhieuNhapSachDTO;
import DTO.SachDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TimeZone;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class quanlydanhmuc extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form quanlydanhmuc
     */
    ResultSet rs;
    DefaultTableModel model;
    DefaultTableModel model2;
    QuanLyDanhMucServices danhmuc;
    ArrayList<SachDTO> dsSach;
Connection conn;
    ArrayList<NXBDTO> dsNhaXB;

    public quanlydanhmuc() {
        initComponents();
        addControls();
        HienThiDanhSachSach();
        // HienThiDanhSachNhaXB();
        HienThiDanhSachChiTietNXB();
        
        this.setDefaultPhieuMuon();
        this.BThemVaoPhieuTam.addActionListener(this);
        this.BThemPhieu.addActionListener(this);
        this.BXoaPhieu.addActionListener(this);
        this.setLocationRelativeTo(null);
        this.BSuaPhieu.addActionListener(this);
        this.CBBNXB.removeAllItems();
        new PhieuNhapSachDAL().DoDuLieuVaoCBBNXB(this.CBBNXB);
        this.TablePhieuNhap.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = TablePhieuNhap.rowAtPoint(evt.getPoint());
                TextMaNhap.setText((String) TablePhieuNhap.getValueAt(row, 0));
                TextTenSach.setText((String) TablePhieuNhap.getValueAt(row, 1));
                TextSL.setText(String.valueOf(TablePhieuNhap.getValueAt(row, 2)) );
                TextDonGia.setText(String.valueOf(TablePhieuNhap.getValueAt(row, 3)));
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                // set formatter to use UTC (instead of JVM default timezone)
                sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
                try {
                    // parse it as midnight (no shift to 01:00)
                    java.util.Date date = sdf.parse((String) TablePhieuNhap.getValueAt(row, 4));
                    java.util.Date dateutil = new java.util.Date(date.getTime());
                    DateNgayGiao.setDate(dateutil);
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }
                TextMaNV.setText((String) TablePhieuNhap.getValueAt(row, 5));
                for(int i=0;i<CBBNXB.getItemCount();i++){
                   NXBDTO nxb=(NXBDTO) CBBNXB.getSelectedItem();
                    System.out.println(TablePhieuNhap.getValueAt(row, 6));
                   if(nxb.getMaNXB().equals(TablePhieuNhap.getValueAt(row, 6))){
                       return;
                   }else{
                        int index=CBBNXB.getSelectedIndex();
                        if(index+1==CBBNXB.getItemCount()){
                            CBBNXB.setSelectedIndex(0);
                        }else{
                        CBBNXB.setSelectedIndex(i+1);
                        }
                   }
                }
                    
            }
        });
        this.TablePhieuTam.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = TablePhieuTam.rowAtPoint(evt.getPoint());
                DefaultTableModel model = (DefaultTableModel) TablePhieuTam.getModel();
                model.removeRow(row);
                TablePhieuTam.setModel(model);
//        int col = jTable1.columnAtPoint(evt.getPoint());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnMain = new javax.swing.JPanel();
        PnDanhMuc = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTheLoai = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        txtNgonNgu = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMaNXB = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtMaNhap = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTaiBan = new javax.swing.JTextField();
        txtTrangThai = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtNamXB = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCAPNHAT = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bang_sach = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bang_nxb = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtmaNXB = new javax.swing.JTextField();
        txtTenNXB = new javax.swing.JTextField();
        btnHuy2 = new javax.swing.JButton();
        btnThemNXB = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        btnSuaNXB = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TextMaNV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        BThemVaoPhieuTam = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DateNgayGiao = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePhieuTam = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        BThemPhieu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        BXoaPhieu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        BSuaPhieu = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        TextMaNhap = new javax.swing.JTextField();
        TextTenSach = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePhieuNhap = new javax.swing.JTable();
        TextSL = new javax.swing.JTextField();
        CBBNXB = new javax.swing.JComboBox<>();
        TextDonGia = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THƯ VIỆN TRƯỜNG THPT DƯỠNG ĐIỀM");
        setMinimumSize(new java.awt.Dimension(1210, 574));

        PnMain.setLayout(new java.awt.CardLayout());

        PnDanhMuc.setPreferredSize(new java.awt.Dimension(1190, 557));

        jPanel8.setMinimumSize(new java.awt.Dimension(1600, 600));
        jPanel8.setPreferredSize(new java.awt.Dimension(1600, 600));

        jPanel10.setLayout(null);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        jLabel2.setText("Tên sách");

        txtTenSach.setEditable(false);
        txtTenSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtTenSach.setPreferredSize(new java.awt.Dimension(4, 18));

        jLabel3.setText("Thể loại");

        jLabel4.setText("Ngôn ngữ");

        jLabel5.setText("Tác giả");

        txtTheLoai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtTheLoai.setPreferredSize(new java.awt.Dimension(4, 18));

        txtTacGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtTacGia.setPreferredSize(new java.awt.Dimension(4, 18));
        txtTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGiaActionPerformed(evt);
            }
        });

        txtNgonNgu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        txtNgonNgu.setMinimumSize(new java.awt.Dimension(4, 18));

        jLabel17.setText("Mã nhà xuất bản");

        txtMaNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel19.setText("Mã nhập");

        txtMaNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel20.setText("Trạng thái");

        jLabel21.setText("Tái bản");

        txtTaiBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        txtTrangThai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel24.setText("Năm xuất bản");

        txtNamXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        btnHuy.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\reset.png")); // NOI18N
        btnHuy.setText("Huỷ");
        btnHuy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNgonNgu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(txtTrangThai, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4)
                            .addComponent(jLabel20))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel21)
                                .addComponent(txtTaiBan, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(txtNamXB))))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgonNgu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaiBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11);
        jPanel11.setBounds(20, 30, 350, 490);

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel10.add(btnXoa);
        btnXoa.setBounds(810, 390, 92, 40);

        btnCAPNHAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sửa sách.png"))); // NOI18N
        btnCAPNHAT.setText("Cập nhật");
        btnCAPNHAT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnCAPNHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAPNHATActionPerformed(evt);
            }
        });
        jPanel10.add(btnCAPNHAT);
        btnCAPNHAT.setBounds(930, 390, 92, 40);

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel10.add(btnThem);
        btnThem.setBounds(680, 390, 92, 40);

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tìm kiếm.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel10.add(btnTimKiem);
        btnTimKiem.setBounds(560, 390, 92, 40);

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/shutdown.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jPanel10.add(btnDangXuat);
        btnDangXuat.setBounds(1030, 500, 120, 31);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        jButton20.setText("Quay lại");
        jButton20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton20);
        jButton20.setBounds(450, 510, 110, 30);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Thông tin sách");
        jPanel10.add(jLabel16);
        jLabel16.setBounds(420, 70, 90, 15);

        bang_sach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bang_sach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bang_sachMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(bang_sach);

        jPanel10.add(jScrollPane4);
        jScrollPane4.setBounds(450, 120, 713, 200);

        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel10.add(jLabel18);
        jLabel18.setBounds(440, 100, 730, 250);

        jLabel23.setBackground(new java.awt.Color(0, 102, 102));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("Chức năng");
        jPanel10.add(jLabel23);
        jLabel23.setBounds(440, 360, 70, 20);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("QUẢN LÝ ĐẦU SÁCH");
        jPanel10.add(jLabel22);
        jLabel22.setBounds(500, 10, 220, 40);

        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel10.add(jLabel39);
        jLabel39.setBounds(540, 370, 510, 80);

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\reset.png")); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6);
        jButton6.setBounds(1066, 60, 50, 30);

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\2397.jpg_wh1200.jpg")); // NOI18N
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5));
        jPanel10.add(jLabel37);
        jLabel37.setBounds(-10, 0, 1200, 570);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1642, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 361, Short.MAX_VALUE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Đầu sách", jPanel8);

        jPanel9.setMinimumSize(new java.awt.Dimension(1600, 600));
        jPanel9.setPreferredSize(new java.awt.Dimension(1600, 577));

        jPanel12.setLayout(null);

        bang_nxb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        bang_nxb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bang_nxbMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(bang_nxb);

        jPanel12.add(jScrollPane3);
        jScrollPane3.setBounds(380, 110, 762, 230);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Tên nhà xuất bản");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Địa chỉ");

        txtDiaChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Số điện thoại");

        txtSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel25.setText("Mã nhà xuất bản");

        txtmaNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        txtTenNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        btnHuy2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\reset.png")); // NOI18N
        btnHuy2.setText("Hủy");
        btnHuy2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnHuy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuy2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT)
                            .addComponent(jLabel25)
                            .addComponent(txtTenNXB)
                            .addComponent(txtmaNXB)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnHuy2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnHuy2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel12.add(jPanel13);
        jPanel13.setBounds(30, 90, 260, 410);

        btnThemNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnThemNXB.setText("Thêm");
        btnThemNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnThemNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNXBActionPerformed(evt);
            }
        });
        jPanel12.add(btnThemNXB);
        btnThemNXB.setBounds(510, 400, 100, 40);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        jButton14.setText("Xóa");
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton14);
        jButton14.setBounds(660, 400, 97, 40);

        btnSuaNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sửa sách.png"))); // NOI18N
        btnSuaNXB.setText("Cập nhật");
        btnSuaNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        btnSuaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNXBActionPerformed(evt);
            }
        });
        jPanel12.add(btnSuaNXB);
        btnSuaNXB.setBounds(790, 400, 97, 40);

        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel12.add(jLabel26);
        jLabel26.setBounds(480, 380, 430, 80);

        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel12.add(jLabel27);
        jLabel27.setBounds(370, 100, 780, 250);

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("Hiển thị thông tin");
        jPanel12.add(jLabel28);
        jLabel28.setBounds(370, 70, 110, 16);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 102));
        jLabel29.setText("Chức năng");
        jPanel12.add(jLabel29);
        jLabel29.setBounds(440, 360, 70, 16);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton1);
        jButton1.setBounds(350, 490, 110, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/shutdown.png"))); // NOI18N
        jButton4.setText("Đăng xuất");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel12.add(jButton4);
        jButton4.setBounds(990, 490, 110, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("QUẢN LÝ NHÀ XUẤT BẢN");
        jPanel12.add(jLabel1);
        jLabel1.setBounds(390, 10, 310, 30);

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\2397.jpg_wh1200.jpg")); // NOI18N
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5));
        jPanel12.add(jLabel34);
        jLabel34.setBounds(-10, 0, 1210, 580);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 407, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nhà xuất bản", jPanel9);

        jPanel2.setPreferredSize(new java.awt.Dimension(1600, 600));
        jPanel2.setLayout(null);

        TextMaNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel2.add(TextMaNV);
        TextMaNV.setBounds(159, 264, 167, 30);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setText("Số lượng");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(60, 170, 60, 16);

        BThemVaoPhieuTam.setText("Thêm vào phiếu tạm");
        jPanel2.add(BThemVaoPhieuTam);
        BThemVaoPhieuTam.setBounds(374, 78, 140, 25);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Nhà xuất bản");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 220, 88, 27);

        DateNgayGiao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel2.add(DateNgayGiao);
        DateNgayGiao.setBounds(430, 220, 131, 30);

        jLabel7.setText("Ngày giao");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(356, 223, 83, 15);

        TablePhieuTam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên sách", "Số lượng", "Đơn giá", "Nhà xuất bản"
            }
        ));
        jScrollPane2.setViewportView(TablePhieuTam);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(50, 370, 510, 124);

        jLabel8.setText("Đơn giá");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(356, 267, 65, 29);

        BThemPhieu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ICON-20190611T140320Z-001\\ICON\\add.png")); // NOI18N
        BThemPhieu.setText("Thêm");
        BThemPhieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel2.add(BThemPhieu);
        BThemPhieu.setBounds(650, 400, 92, 40);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Danh sách nhập sách tạm thời");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(80, 330, 200, 26);

        BXoaPhieu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ICON-20190611T140320Z-001\\ICON\\delete.png")); // NOI18N
        BXoaPhieu.setText("Xóa");
        BXoaPhieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel2.add(BXoaPhieu);
        BXoaPhieu.setBounds(780, 400, 92, 40);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Danh sách phiếu nhập");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(590, 80, 270, 32);

        BSuaPhieu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ICON-20190611T140320Z-001\\ICON\\sửa sách.png")); // NOI18N
        BSuaPhieu.setText("Cập nhật");
        BSuaPhieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        BSuaPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSuaPhieuActionPerformed(evt);
            }
        });
        jPanel2.add(BSuaPhieu);
        BSuaPhieu.setBounds(890, 400, 92, 40);

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel35.setText("Mã phiếu nhập");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(60, 80, 95, 16);

        TextMaNhap.setEditable(false);
        TextMaNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel2.add(TextMaNhap);
        TextMaNhap.setBounds(159, 73, 168, 30);

        TextTenSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        TextTenSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTenSachActionPerformed(evt);
            }
        });
        jPanel2.add(TextTenSach);
        TextTenSach.setBounds(159, 121, 168, 30);

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel36.setText("Tên sách");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(60, 130, 70, 16);

        TablePhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(TablePhieuNhap);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(600, 130, 557, 170);

        TextSL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel2.add(TextSL);
        TextSL.setBounds(159, 164, 168, 30);

        CBBNXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBBNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel2.add(CBBNXB);
        CBBNXB.setBounds(159, 215, 168, 30);

        TextDonGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        jPanel2.add(TextDonGia);
        TextDonGia.setBounds(430, 260, 92, 30);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\back.png")); // NOI18N
        jButton2.setText("Quay lại");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(630, 500, 110, 40);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\shutdown.png")); // NOI18N
        jButton3.setText("Đăng xuất");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(1060, 500, 110, 40);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("QUẢN LÝ PHIẾU NHẬP SÁCH");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(436, 23, 307, 29);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel31.setText("Mã thủ thư");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(60, 280, 80, 16);

        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel2.add(jLabel30);
        jLabel30.setBounds(40, 360, 530, 140);

        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel2.add(jLabel32);
        jLabel32.setBounds(590, 120, 580, 190);

        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jPanel2.add(jLabel38);
        jLabel38.setBounds(620, 380, 540, 80);

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 102));
        jLabel41.setText("Chức năng");
        jPanel2.add(jLabel41);
        jLabel41.setBounds(680, 340, 70, 30);

        jButton5.setText("IN Phiếu Nhập Sách");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(1000, 400, 130, 40);

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Icon\\2397.jpg_wh1200.jpg")); // NOI18N
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 5));
        jPanel2.add(jLabel33);
        jLabel33.setBounds(0, 0, 1190, 580);

        jTabbedPane1.addTab("Phiếu nhập sách", jPanel2);

        javax.swing.GroupLayout PnDanhMucLayout = new javax.swing.GroupLayout(PnDanhMuc);
        PnDanhMuc.setLayout(PnDanhMucLayout);
        PnDanhMucLayout.setHorizontalGroup(
            PnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnDanhMucLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnDanhMucLayout.setVerticalGroup(
            PnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnDanhMucLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );

        PnMain.add(PnDanhMuc, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuy2ActionPerformed
        // TODO add your handling code here:
        // HienThiDanhSachNhaXB();
    }//GEN-LAST:event_btnHuy2ActionPerformed

    private void btnSuaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNXBActionPerformed
        // TODO add your handling code here:
        CapNhatNhaXuatBan();
        HienThiDanhSachChiTietNXB();
    }//GEN-LAST:event_btnSuaNXBActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        XoaNhaXuatBan();
        HienThiDanhSachChiTietNXB();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnThemNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNXBActionPerformed
        // TODO add your handling code here:
        ThemNhaXuatBan();
        HienThiDanhSachChiTietNXB();
    }//GEN-LAST:event_btnThemNXBActionPerformed

    private void bang_nxbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bang_nxbMouseClicked
        // TODO add your handling code here:
        int i = bang_nxb.getSelectedRow();
        TableModel model = bang_nxb.getModel();
        txtmaNXB.setText(model.getValueAt(i, 0).toString());
        txtTenNXB.setText(model.getValueAt(i, 1).toString());
        txtDiaChi.setText(model.getValueAt(i, 2).toString());
        txtSDT.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_bang_nxbMouseClicked

    private void bang_sachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bang_sachMouseClicked
        int i = bang_sach.getSelectedRow();
        TableModel model = bang_sach.getModel();
       // txtMaSach.setText(model.getValueAt(i, 0).toString());
        txtTheLoai.setText(model.getValueAt(i, 1).toString());
        txtMaNhap.setText(model.getValueAt(i, 2).toString());
        txtMaNXB.setText(model.getValueAt(i, 3).toString());
        txtTenSach.setText(model.getValueAt(i, 4).toString());
        txtTacGia.setText(model.getValueAt(i, 5).toString());
        txtNamXB.setText(model.getValueAt(i, 6).toString());
        txtTrangThai.setText(model.getValueAt(i, 7).toString());
        txtNgonNgu.setText(model.getValueAt(i, 8).toString());
        txtTaiBan.setText(model.getValueAt(i, 9).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_bang_sachMouseClicked

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        // HienThiDanhSachSach();
//        txtMaSach.setText("");
        txtTheLoai.setText("");
        txtMaNhap.setText("");
        txtMaNXB.setText("");
        txtTenSach.setText("");
        txtTacGia.setText("");
        txtNamXB.setText("");
        txtTrangThai.setText("");
        txtNgonNgu.setText("");
        txtTaiBan.setText("");
        txtTenSach.requestFocus();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed

        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
    xuLyTimKiemSach();

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        ThemSach();
        HienThiDanhSachSach();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCAPNHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAPNHATActionPerformed
        // TODO add your handling code here:
        SuaSach();
        HienThiDanhSachSach();
    }//GEN-LAST:event_btnCAPNHATActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        XoaSach();
        HienThiDanhSachSach();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGiaActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        new MenuThuThu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MenuThuThu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MenuThuThu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        HienThiDanhSachSach();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
             // TODO add your handling code here:
      try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            String strConn="jdbc:oracle:thin:@localhost:1521/orcl11g";
           conn=DriverManager.getConnection(strConn,"TRA","123456");
            if(conn!=null)
			{
				System.out.println("Kết nối tới Oracle thành công");
			}
			else
			{
				System.out.println("Kết nối tới Oracle thất bại");
			}
           String reportPath="C:\\Users\\Admin\\Desktop\\thuvienduongdiem_12_6_2019\\database\\src\\Report\\PhieuNhapSach.jrxml";
          HashMap pm= new HashMap();
          pm.put("MaPhieuNhap",(String) this.TablePhieuNhap.getValueAt(this.TablePhieuNhap.getSelectedRow(), 0));
           JasperReport jr= JasperCompileManager.compileReport(reportPath);
           JasperPrint jp=JasperFillManager.fillReport(jr,pm,conn);
           JasperViewer.viewReport(jp,false);
           conn.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TextTenSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTenSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTenSachActionPerformed

    private void BSuaPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSuaPhieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BSuaPhieuActionPerformed
    /*==============================================QUẢN LÝ DANH MỤC====================================================================*/
 void setDefaultPhieuMuon(){
        DefaultTableModel model=new DefaultTableModel();
        String[] title={"Mã phiếu mượn","Tên sách","Số lượng","Đồng Giá","Ngày Giao","Mã nhân viên","Mã nhà xuất bản"};
        model.setColumnIdentifiers(title);
        ArrayList<PhieuNhapSachDTO> ar=new PhieuNhapSachBLL().getAllPhieu();
        for(int i=0;i<ar.size();i++){
            PhieuNhapSachDTO pn=ar.get(i);
            String maphieu=pn.getMaPhieu();
            String tensach=pn.getTenSach();
            int soluong=pn.getSL();
            int donggia=pn.getDongGia();
            String ngaygiao=pn.getNgayGiao();
            String manv=pn.getMaNV();
            String manxb=pn.getMaNXB();
            Object[]temp={maphieu,tensach,soluong,donggia,ngaygiao,manv,manxb};
            model.addRow(temp);
        }
        this.TablePhieuNhap.setModel(model);
    }
//
//    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getSource().equals(BThemVaoPhieuTam)){
            String strDate = new SimpleDateFormat("dd-MM-yyyy").format(new java.sql.Date(this.DateNgayGiao.getDate().getTime()));
            NXBDTO nxb=(NXBDTO) CBBNXB.getSelectedItem();
            PhieuNhapSachDTO pn=new PhieuNhapSachDTO(null, this.TextTenSach.getText(), Integer.parseInt(this.TextSL.getText()), Integer.parseInt(this.TextDonGia.getText()), strDate, this.TextMaNV.getText(), nxb.getMaNXB());
            Object[]temp={pn.getTenSach(),pn.getSL(),pn.getDongGia(),pn.getMaNXB()};
            DefaultTableModel model=(DefaultTableModel) this.TablePhieuTam.getModel();
            model.addRow(temp);
            this.TablePhieuTam.setModel(model);
            
        }
        if(ae.getSource().equals(BThemPhieu)){
            String ma=DAL.Database.TaoMa("phieunhap");
            for(int i=0;i<this.TablePhieuTam.getRowCount();i++){
                String strDate = new SimpleDateFormat("dd-MM-yyyy").format(new java.sql.Date(this.DateNgayGiao.getDate().getTime()));
            new PhieuNhapSachBLL().ThemPhieuNhap(new PhieuNhapSachDTO(ma, (String) this.TablePhieuTam.getValueAt(i, 0), (int) this.TablePhieuTam.getValueAt(i, 1), (int )this.TablePhieuTam.getValueAt(i, 2), strDate, this.TextMaNV.getText(),(String) this.TablePhieuTam.getValueAt(i, 3)));
//                String sql="INSERT INTO PHIEUNHAPSACH VALUES(?,?,?,?,?,?,?)";
//                try {
//                    PreparedStatement st=conectionJDBC().prepareStatement(sql);
//                    st.setString(1, ma);
//                    st.setString(2, (String) this.TablePhieuTam.getValueAt(i, 0));
//                    st.setInt(3, Integer.parseInt((String) this.TablePhieuTam.getValueAt(i, 1)));
//                    st.setInt(4, Integer.parseInt((String) this.TablePhieuTam.getValueAt(i, 2)));
//                    st.setString(5, (String) this.TablePhieuTam.getValueAt(i, 3));
//                    st.executeUpdate();
//                } catch (SQLException ex) {
//                    Logger.getLogger(quanliphieunhapsach.class.getName()).log(Level.SEVERE, null, ex);
//                }
                this.setDefaultPhieuMuon();
            }
        }
        if(ae.getSource().equals(BXoaPhieu)){
            new PhieuNhapSachBLL().XoaPhieuNhap((String) this.TablePhieuNhap.getValueAt(this.TablePhieuNhap.getSelectedRow(), 0));
                this.setDefaultPhieuMuon();
        }
        if(ae.getSource().equals(BSuaPhieu)){
            String strDate = new SimpleDateFormat("dd-MM-yyyy").format(new java.sql.Date(this.DateNgayGiao.getDate().getTime()));
            new PhieuNhapSachBLL().SuaPhieuNhap((String)this.TablePhieuNhap.getValueAt(this.TablePhieuNhap.getSelectedRow(), 0), new PhieuNhapSachDTO((String)this.TablePhieuNhap.getValueAt(this.TablePhieuNhap.getSelectedRow(), 0), this.TextTenSach.getText(), Integer.parseInt(this.TextSL.getText()), Integer.parseInt(this.TextDonGia.getText()), strDate, this.TextMaNV.getText(), ((NXBDTO)CBBNXB.getSelectedItem()).getMaNXB()),(String)this.TablePhieuNhap.getValueAt(this.TablePhieuNhap.getSelectedRow(), 1));
            this.setDefaultPhieuMuon();
        }
    }
 /*TÌM KIẾM SÁCH */
    protected void xuLyTimKiemSach() {
        danhmuc = new QuanLyDanhMucServices();
        dsSach = danhmuc.TimKiemSachTheoTen(txtTenSach.getText(),txtTacGia.getText(),txtTheLoai.getText(),
                txtMaNXB.getText(),txtMaNhap.getText(),txtTrangThai.getText(),txtNamXB.getText(),txtNgonNgu.getText(),txtTaiBan.getText());
        model.setRowCount(0);
        for (SachDTO sa : dsSach) {
            Vector<Object> vec = new Vector<Object>();
           vec.add(sa.getMaSach());
                vec.add(sa.getTheLoai());
                vec.add(sa.getMaNhap());
                vec.add(sa.getMaNXB());
                vec.add(sa.getTenSach());
                vec.add(sa.getTacGia());
                vec.add(sa.getNamXB());
                vec.add(sa.getTrangThai());
                vec.add(sa.getNgonNgu());
                vec.add(sa.getTaiBan());
            model.addRow(vec);
        }
    }

    /*BẢNG SÁCH*/
    public void HienThiDanhSachSach() {
        try {
            danhmuc = new QuanLyDanhMucServices();
            dsSach = danhmuc.layToanBoSach();
            model.setRowCount(0);
            for (SachDTO sa : dsSach) {
                Vector<Object> vec = new Vector<Object>();
                vec.add(sa.getMaSach());
                vec.add(sa.getTheLoai());
                vec.add(sa.getMaNhap());
                vec.add(sa.getMaNXB());
                vec.add(sa.getTenSach());
                vec.add(sa.getTacGia());
                vec.add(sa.getNamXB());
                vec.add(sa.getTrangThai());
                vec.add(sa.getNgonNgu());
                vec.add(sa.getTaiBan());
                model.addRow(vec);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /*XOÁ SÁCH*/
    public void XoaSach() {
        try {
            danhmuc = new QuanLyDanhMucServices();
            danhmuc.xoaSach((String) this.bang_sach.getValueAt(this.bang_sach.getSelectedRow(), 0));
            JOptionPane.showMessageDialog(null, "Đã xoá!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Thông báo lỗi:\n" + e.toString());
            System.out.println(e);
        }

    }

    /*THÊM SÁCH*/   
       public void ThemSach()
      {
              try {
              danhmuc=new QuanLyDanhMucServices();
               danhmuc.themSach( txtTheLoai.getText(), txtMaNhap.getText(),
                 txtMaNXB.getText(),txtTenSach.getText(),txtTacGia.getText(),
                 txtNamXB.getText(),txtTrangThai.getText() ,txtNgonNgu.getText(),txtTaiBan.getText());
                JOptionPane.showMessageDialog(null,"Thêm sách thành công!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Thêm không thành công");
                e.printStackTrace();
            }
         
      }

    /*CẬP NHẬT SÁCH*/
    public void SuaSach() {
        try {
            danhmuc = new QuanLyDanhMucServices();
            danhmuc.suaSach((String) this.bang_sach.getValueAt(this.bang_sach.getSelectedRow(), 0), txtTheLoai.getText(), txtMaNhap.getText(),
                    txtMaNXB.getText(), txtTenSach.getText(), txtTacGia.getText(),
                    txtNamXB.getText(), txtTrangThai.getText(), txtNgonNgu.getText(), txtTaiBan.getText());
            JOptionPane.showMessageDialog(null, " thành công!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "không thành công");
            e.printStackTrace();
        }

    }

    /*BẢNG CHI TIẾT NXB*/
    public void HienThiDanhSachChiTietNXB() {
        try {
            danhmuc = new QuanLyDanhMucServices();
            dsNhaXB = danhmuc.LayToanBoctNhaXB();
            model2.setRowCount(0);
            for (NXBDTO xb : dsNhaXB) {
                Vector<Object> vec = new Vector<Object>();
                vec.add(xb.getMaNXB());
                vec.add(xb.getTenNXB());
                vec.add(xb.getDiaChi());
                vec.add(xb.getSDT());

                model2.addRow(vec);
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /*TÌM KIẾM THEO NXB*/
//     protected void xuLyTimKiemTheoNXB() {
//	
//         danhmuc=new QuanLyDanhMucServices();  
//        dsNhaXB=danhmuc.HienThiChiTietNhaXB(cBoNhaXB.getSelectedItem().toString());
//        model2.setRowCount(0);
//    for(NhaXuatBanDTO sa:dsNhaXB)			
//    {
//            Vector<String>vec=new Vector<String>();
//             vec.add(sa.getManxb());
//             vec.add(sa.getTennxb());
//             vec.add(sa.getDiachi());                                              
//             vec.add(sa.getSdt());
//             model2.addRow(vec);
//    }
//    
//}  
/*==================================================================================================*/
 /*THEM NHA XUAT BAN*/
    /*THEM NHA XUAT BAN*/
   public void ThemNhaXuatBan()
      {
              try {
                danhmuc=new QuanLyDanhMucServices();
               danhmuc.themNXB( txtTenNXB.getText(), txtDiaChi.getText(), txtSDT.getText());
                JOptionPane.showMessageDialog(null,"Thêm nhà xu?t b?n thành công!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Thêm không thành công");
                e.printStackTrace();
            }
         
      }   

   /*XOA NHA XUAT BAN*/
   public void XoaNhaXuatBan()
      {
              try {
                danhmuc=new QuanLyDanhMucServices();
                int i=bang_nxb.getSelectedRow();
               danhmuc.xoaNXB(bang_nxb.getValueAt(i,0).toString());
                JOptionPane.showMessageDialog(null,"Xoá nhà xu?t b?n thành công!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Xoá không thành công");
                e.printStackTrace();
            }
         
      }  

    /*CAP NHAT NHA XUAT BAN*/
    public void CapNhatNhaXuatBan() {
        try {
            danhmuc = new QuanLyDanhMucServices();
            danhmuc.suaNXB(txtmaNXB.getText(), txtTenNXB.getText(), txtDiaChi.getText(), txtSDT.getText());
            JOptionPane.showMessageDialog(null, "Cap nhat thành công!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, " không thành công");
            e.printStackTrace();
        }

    }

    protected void xuLyTimKiemTheoTenNXB() {
        danhmuc = new QuanLyDanhMucServices();
        dsNhaXB = danhmuc.TimKiemNXBTheoTen(txtTenNXB.getText());
        model.setRowCount(0);
        for (NXBDTO xb : dsNhaXB) {
            Vector<Object> vec = new Vector<Object>();
            vec.add(xb.getMaNXB());
            vec.add(xb.getTenNXB());
            vec.add(xb.getDiaChi());
            vec.add(xb.getSDT());
            model2.addRow(vec);
        }
    }

    /*CONTROLS*/
    private void addControls() {
        // TODO Auto-generated method stub

        model = new DefaultTableModel();
        model.addColumn("Mã sách");
        model.addColumn("Thể loại");
        model.addColumn("Mã nhập");
        model.addColumn("Mã NXB");
        model.addColumn("Tên sách");
        model.addColumn("Tên tác giả");
        model.addColumn("Năm XB");
        model.addColumn("Trạng thái");
        model.addColumn("Ngôn ngữ");
        model.addColumn("Tái bản");
        bang_sach.setModel(model);
        //////////////////////////                 
        model2 = new DefaultTableModel();
        model2.addColumn("Mã NXB");
        model2.addColumn("Tên NXB");
        model2.addColumn("Địa chỉ");
        model2.addColumn("SĐT");
        bang_nxb.setModel(model2);

    }

    /*=========================================================================================*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlydanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlydanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlydanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlydanhmuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                quanlydanhmuc tt = new quanlydanhmuc();
                tt.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                tt.setLocationRelativeTo(null);
                new quanlydanhmuc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSuaPhieu;
    private javax.swing.JButton BThemPhieu;
    private javax.swing.JButton BThemVaoPhieuTam;
    private javax.swing.JButton BXoaPhieu;
    private javax.swing.JComboBox<String> CBBNXB;
    private com.toedter.calendar.JDateChooser DateNgayGiao;
    private javax.swing.JPanel PnDanhMuc;
    private javax.swing.JPanel PnMain;
    private javax.swing.JTable TablePhieuNhap;
    private javax.swing.JTable TablePhieuTam;
    private javax.swing.JTextField TextDonGia;
    private javax.swing.JTextField TextMaNV;
    private javax.swing.JTextField TextMaNhap;
    private javax.swing.JTextField TextSL;
    private javax.swing.JTextField TextTenSach;
    private javax.swing.JTable bang_nxb;
    private javax.swing.JTable bang_sach;
    private javax.swing.JButton btnCAPNHAT;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnHuy2;
    private javax.swing.JButton btnSuaNXB;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemNXB;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaNXB;
    private javax.swing.JTextField txtMaNhap;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtNgonNgu;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTaiBan;
    private javax.swing.JTextField txtTenNXB;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTheLoai;
    private javax.swing.JTextField txtTrangThai;
    private javax.swing.JTextField txtmaNXB;
    // End of variables declaration//GEN-END:variables
}
